export class GetCountries {
    static getAllCountries(): any {
        return [
            { code: 'AL', name: 'Albania', cities: ['Tirana', 'Durres', 'Vlore', 'Shkoder', 'Elbasan'] },
            { code: 'AD', name: 'Andorra', cities: ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'La Massana', 'Sant Julia de Loria'] },
            { code: 'AM', name: 'Armenia', cities: ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Hrazdan'] },
            { code: 'AT', name: 'Austria', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'] },
            { code: 'AZ', name: 'Azerbaijan', cities: ['Baku', 'Ganja', 'Sumqayit', 'Lankaran', 'Mingachevir'] },
            { code: 'BY', name: 'Belarus', cities: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno'] },
            { code: 'BE', name: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liege'] },
            { code: 'BA', name: 'Bosnia and Herzegovina', cities: ['Sarajevo', 'Banja Luka', 'Mostar', 'Tuzla', 'Zenica'] },
            { code: 'BG', name: 'Bulgaria', cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'] },
            { code: 'HR', name: 'Croatia', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar'] },
            { code: 'CY', name: 'Cyprus', cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta'] },
            { code: 'CZ', name: 'Czechia', cities: ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Liberec'] },
            { code: 'DK', name: 'Denmark', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'] },
            { code: 'EE', name: 'Estonia', cities: ['Tallinn', 'Tartu', 'Narva', 'Parnu', 'Viljandi'] },
            { code: 'FI', name: 'Finland', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Turku'] },
            { code: 'FR', name: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice'] },
            { code: 'GE', name: 'Georgia', cities: ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi', 'Zugdidi'] },
            { code: 'DE', name: 'Germany', cities: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne'] },
            { code: 'GR', name: 'Greece', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa'] },
            { code: 'HU', name: 'Hungary', cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pecs'] },
            { code: 'IS', name: 'Iceland', cities: ['Reykjavik', 'Kopavogur', 'Hafnarfjordur', 'Akureyri', 'Keflavik'] },
            { code: 'IE', name: 'Ireland', cities: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford'] },
            { code: 'IT', name: 'Italy', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Florence'] },
            { code: 'XK', name: 'Kosovo', cities: ['Pristina', 'Prizren', 'Ferizaj', 'Peja', 'Gjakova'] },
            { code: 'LV', name: 'Latvia', cities: ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava', 'Jurmala'] },
            { code: 'LI', name: 'Liechtenstein', cities: ['Vaduz', 'Schaan', 'Balzers', 'Triesen', 'Eschen'] },
            { code: 'LT', name: 'Lithuania', cities: ['Vilnius', 'Kaunas', 'Klaipeda', 'Siauliai', 'Panevezys'] },
            { code: 'LU', name: 'Luxembourg', cities: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck'] },
            { code: 'MT', name: 'Malta', cities: ['Valletta', 'Sliema', 'Birkirkara', 'Mosta', 'St. Julian\'s'] },
            { code: 'MD', name: 'Moldova', cities: ['Chisinau', 'Balti', 'Tiraspol', 'Bender', 'Cahul'] },
            { code: 'MC', name: 'Monaco', cities: ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille', 'Moneghetti'] },
            { code: 'ME', name: 'Montenegro', cities: ['Podgorica', 'Niksic', 'Budva', 'Kotor', 'Bar'] },
            { code: 'NL', name: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'] },
            { code: 'MK', name: 'North Macedonia', cities: ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Ohrid'] },
            { code: 'NO', name: 'Norway', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen'] },
            { code: 'PL', name: 'Poland', cities: ['Warsaw', 'Krakow', 'Wroclaw', 'Poznan', 'Gdansk'] },
            { code: 'PT', name: 'Portugal', cities: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Faro'] },
            { code: 'RO', name: 'Romania', cities: ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi', 'Constanta'] },
            { code: 'RU', name: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan'] },
            { code: 'SM', name: 'San Marino', cities: ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano', 'Fiorentino'] },
            { code: 'RS', name: 'Serbia', cities: ['Belgrade', 'Novi Sad', 'Nis', 'Kragujevac', 'Subotica'] },
            { code: 'SK', name: 'Slovakia', cities: ['Bratislava', 'Kosice', 'Presov', 'Zilina', 'Nitra'] },
            { code: 'SI', name: 'Slovenia', cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper'] },
            { code: 'ES', name: 'Spain', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Bilbao'] },
            { code: 'SE', name: 'Sweden', cities: ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala', 'Vasteras'] },
            { code: 'CH', name: 'Switzerland', cities: ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern'] },
            { code: 'TR', name: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya'] },
            { code: 'UA', name: 'Ukraine', cities: ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk'] },
            { code: 'GB', name: 'United Kingdom', cities: ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Edinburgh'] },
            { code: 'VA', name: 'Vatican City', cities: ['Vatican City'] }
        ];
    }
}